"""empty message

Revision ID: 45027f8acd52
Revises: 48766779a032
Create Date: 2020-01-05 02:24:38.791323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45027f8acd52'
down_revision = '48766779a032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('img_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=100), nullable=True),
    sa.Column('raddress', sa.String(length=100), nullable=True),
    sa.Column('oaddress', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('etel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=100), nullable=True),
    sa.Column('s_class_', sa.String(length=100), nullable=True),
    sa.Column('s_year', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['Parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=100), nullable=True),
    sa.Column('bg', sa.String(length=100), nullable=True),
    sa.Column('bp', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('gen', sa.String(length=50), nullable=True),
    sa.Column('lga', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('ail', sa.String(length=10), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('school_address', sa.String(length=200), nullable=True),
    sa.Column('class_', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['Parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=100), nullable=True),
    sa.Column('sub_email', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['Parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student')
    op.drop_table('news')
    op.drop_table('siblings')
    op.drop_table('parent')
    op.drop_table('subscriber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sub_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sub_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], name='subscriber_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('parent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('raddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('oaddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('family', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('etel', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('siblings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('s_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('s_class_', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('s_year', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], name='siblings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('news',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('img_data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dob', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bg', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bp', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lga', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('ail', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('school', mysql.TEXT(), nullable=True),
    sa.Column('school_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('class_', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], name='student_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Subscriber')
    op.drop_table('Student')
    op.drop_table('Siblings')
    op.drop_table('Parent')
    op.drop_table('News')
    # ### end Alembic commands ###
